In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedGroupKFold, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import m2cgen as m2c

# Binary Sprint Classes Model

In [ ]:
df = pd.read_csv("../data/features/engineered_features_v1.csv")

In [ ]:
X = df.drop(columns=["trial_num", "start", "end", "sprint"])
y = df["sprint"]
groups = df["trial_num"]
sgkf = StratifiedGroupKFold(n_splits=4)

In [ ]:
importances_list = []

for train_idx, test_idx in sgkf.split(X, y, groups=groups):
    X_train = X.iloc[train_idx]
    y_train = y.iloc[train_idx]
    X_test = X.iloc[test_idx]
    y_test = y.iloc[test_idx]

    clf = RandomForestClassifier(random_state=1)
    clf.fit(X_train, y_train)

    importances_list.append(clf.feature_importances_)
    print(classification_report(y_test, clf.predict(X_test)))

importances_df = pd.DataFrame(importances_list, columns=X.columns).T

for col in importances_df.columns:
    importances_df[f"{col}_above_baseline"] = importances_df[col].apply(
        lambda x: "yes" if x > 1 / len(importances_df) else "no"
    )
importances_df

In [ ]:
passing_features = ['clean_accel_rms', 'clean_accel_mean', 'raw_accel_rms', 'raw_accel_std', 'raw_accel_mean', 'clean_accel_std', 'clean_accel_max', 'raw_accel_max']
X = df.loc[:, passing_features]
X.corr()

In [ ]:
selected_features = ["clean_accel_rms", "clean_accel_max", "clean_accel_std"]
X = df[selected_features]

In [ ]:
depths = list(range(1, 10, 1))
estimators = list(range(70, 90, 2))

param_grid = {"max_depth": depths, "n_estimators": estimators}

grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=1),
    param_grid=param_grid,
    cv=sgkf,
    scoring="accuracy",
    n_jobs=-1,
)

grid_search.fit(X, y, groups=groups)

In [ ]:
clf = RandomForestClassifier(max_depth=2, n_estimators=70, random_state=1)
clf.fit(X, y)

In [ ]:
model_src = m2c.export_to_dart(clf)

with open("../models/binary_sprint_classifier.dart", "w") as file:
    file.write(model_src)

# Multi Classes Sprint Phases Model

Can not reliably tell acceleration and cruising apart. Primary reason is likely the arbitrary visual labeling.

In [ ]:
df = pd.read_csv("../data/features/engineered_features_v2.csv")

In [ ]:
X = df.drop(columns=["trial_num", "start", "end", "sprint"])
y = df["sprint"]
groups = df["trial_num"]
sgkf = StratifiedGroupKFold(n_splits=4)

In [ ]:
importances_list = []

for train_idx, test_idx in sgkf.split(X, y, groups=groups):
    X_train = X.iloc[train_idx]
    y_train = y.iloc[train_idx]
    X_test = X.iloc[test_idx]
    y_test = y.iloc[test_idx]

    clf = RandomForestClassifier(random_state=1)
    clf.fit(X_train, y_train)

    importances_list.append(clf.feature_importances_)
    print(classification_report(y_test, clf.predict(X_test)))

importances_df = pd.DataFrame(importances_list, columns=X.columns).T

for col in importances_df.columns:
    importances_df[f"{col}_above_baseline"] = importances_df[col].apply(
        lambda x: "yes" if x > 1 / len(importances_df) else "no"
    )
importances_df

In [ ]:
passing_features = ['clean_accel_rms', 'clean_accel_mean', 'raw_accel_rms', 'raw_accel_std', 'raw_accel_mean', 'clean_accel_std', 'clean_accel_max', 'raw_accel_max']
X = df.loc[:, passing_features]
X.corr()

In [ ]:
selected_features = ["clean_accel_rms", "clean_accel_max", "clean_accel_std"]
X = df.loc[:, selected_features]

In [ ]:
depths = list(range(1, 10, 1))
estimators = list(range(70, 90, 2))

param_grid = {"max_depth": depths, "n_estimators": estimators}

grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=1),
    param_grid=param_grid,
    cv=sgkf,
    scoring="accuracy",
    n_jobs=-1,
)

grid_search.fit(X, y, groups=groups)

In [ ]:
clf = RandomForestClassifier(random_state=1)
clf.fit(X, y)

In [ ]:
# model_src = m2c.export_to_dart(clf)

# with open("../models/binary_sprint_classifier.dart", "w") as file:
#     file.write(model_src)

# Binary Sprint Classes Model

In [2]:
df = pd.read_csv("../data/features/engineered_features_v3.csv")

In [5]:
X = df.drop(columns=["trial_num", "start", "end", "intense"])
y = df["intense"]
groups = df["trial_num"]
sgkf = StratifiedGroupKFold(n_splits=4)

In [7]:
importances_list = []

for train_idx, test_idx in sgkf.split(X, y, groups=groups):
    X_train = X.iloc[train_idx]
    y_train = y.iloc[train_idx]
    X_test = X.iloc[test_idx]
    y_test = y.iloc[test_idx]

    clf = RandomForestClassifier(random_state=1)
    clf.fit(X_train, y_train)

    importances_list.append(clf.feature_importances_)
    print(classification_report(y_test, clf.predict(X_test)))

importances_df = pd.DataFrame(importances_list, columns=X.columns).T

for col in importances_df.columns:
    importances_df[f"{col}_above_baseline"] = importances_df[col].apply(
        lambda x: "yes" if x > 1 / len(importances_df) else "no"
    )
importances_df

              precision    recall  f1-score   support

           0       0.97      0.98      0.97        89
           1       0.97      0.95      0.96        62

    accuracy                           0.97       151
   macro avg       0.97      0.96      0.97       151
weighted avg       0.97      0.97      0.97       151

              precision    recall  f1-score   support

           0       0.99      1.00      0.99        81
           1       1.00      0.98      0.99        52

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

              precision    recall  f1-score   support

           0       0.96      0.98      0.97        89
           1       0.96      0.93      0.95        57

    accuracy                           0.96       146
   macro avg       0.96      0.95      0.96       146
weighted avg       0.96      0.96      0.96       146

              precision    recall  f1-score   support

           0       0.99      0.98      0.98        87
           1       0.97      0.98      0.98        62

    accuracy                           0.98       149
   macro avg       0.98      0.98      0.98       149
weighted avg       0.98      0.98      0.98       149

,0,1,2,3,0_above_baseline,1_above_baseline,2_above_baseline,3_above_baseline
raw_accel_mean,0.044148,0.078072,0.090262,0.061352,no,yes,yes,yes
raw_accel_max,0.075711,0.065734,0.047832,0.143050,yes,yes,no,yes
raw_accel_std,0.003929,0.003631,0.005321,0.029361,no,no,no,no
raw_accel_rms,0.159763,0.177058,0.145269,0.105643,yes,yes,yes,yes
clean_accel_mean,0.060077,0.078154,0.065757,0.031105,yes,yes,yes,no
clean_accel_max,0.038939,0.006563,0.022539,0.104564,no,no,no,yes
clean_accel_std,0.021474,0.025607,0.020198,0.009215,no,no,no,no
clean_accel_rms,0.116435,0.120839,0.162403,0.076577,yes,yes,yes,yes
clean_accel_zcr_x,0.002815,0.005923,0.004103,0.006046,no,no,no,no
clean_accel_zcr_y,0.001502,0.002765,0.001240,0.002636,no,no,no,no
clean_accel_zcr_z,0.007069,0.004477,0.006272,0.002632,no,no,no,no
gyro_mean,0.039258,0.075631,0.041762,0.058585,no,yes,no,yes
gyro_max,0.129758,0.127750,0.115568,0.157954,yes,yes,yes,yes
gyro_std,0.168654,0.100750,0.109728,0.107420,yes,yes,yes,yes
gyro_rms,0.121018,0.114333,0.152615,0.093919,yes,yes,yes,yes
gyro_zcr_x,0.003518,0.003752,0.002353,0.003640,no,no,no,no
gyro_zcr_y,0.005163,0.007621,0.005375,0.005840,no,no,no,no
gyro_zcr_z,0.000768,0.001341,0.001401,0.000460,no,no,no,no

In [8]:
passing_features = ['gyro_std', 'raw_accel_rms', 'gyro_max', 'gyro_rms', 'clean_accel_rms', 'raw_accel_max', 'clean_accel_mean', 'raw_accel_mean', 'gyro_mean']
X = df.loc[:, passing_features]
X.corr()

,gyro_std,raw_accel_rms,gyro_max,gyro_rms,clean_accel_rms,raw_accel_max,clean_accel_mean,raw_accel_mean,gyro_mean
gyro_std,1.000000,0.934150,0.986477,0.959447,0.943537,0.958414,0.928435,0.917619,0.940012
raw_accel_rms,0.934150,1.000000,0.948347,0.988031,0.995141,0.955154,0.996179,0.998068,0.988560
gyro_max,0.986477,0.948347,1.000000,0.971041,0.958141,0.968192,0.945146,0.933661,0.956211
gyro_rms,0.959447,0.988031,0.971041,1.000000,0.992067,0.966568,0.990433,0.981764,0.997976
clean_accel_rms,0.943537,0.995141,0.958141,0.992067,1.000000,0.971357,0.998171,0.988714,0.991701
raw_accel_max,0.958414,0.955154,0.968192,0.966568,0.971357,1.000000,0.958571,0.937053,0.957617
clean_accel_mean,0.928435,0.996179,0.945146,0.990433,0.998171,0.958571,1.000000,0.992931,0.993211
raw_accel_mean,0.917619,0.998068,0.933661,0.981764,0.988714,0.937053,0.992931,1.000000,0.984499
gyro_mean,0.940012,0.988560,0.956211,0.997976,0.991701,0.957617,0.993211,0.984499,1.000000

In [19]:
selected_features = ["gyro_std", 'raw_accel_mean']
X = df[selected_features]

In [20]:
importances_list = []

for train_idx, test_idx in sgkf.split(X, y, groups=groups):
    X_train = X.iloc[train_idx]
    y_train = y.iloc[train_idx]
    X_test = X.iloc[test_idx]
    y_test = y.iloc[test_idx]

    clf = RandomForestClassifier(random_state=1)
    clf.fit(X_train, y_train)

    importances_list.append(clf.feature_importances_)
    print(classification_report(y_test, clf.predict(X_test)))

importances_df = pd.DataFrame(importances_list, columns=X.columns).T

for col in importances_df.columns:
    importances_df[f"{col}_above_baseline"] = importances_df[col].apply(
        lambda x: "yes" if x > 1 / len(importances_df) else "no"
    )
importances_df

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        89
           1       0.97      0.97      0.97        62

    accuracy                           0.97       151
   macro avg       0.97      0.97      0.97       151
weighted avg       0.97      0.97      0.97       151

              precision    recall  f1-score   support

           0       0.99      1.00      0.99        81
           1       1.00      0.98      0.99        52

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

              precision    recall  f1-score   support

           0       0.96      0.98      0.97        89
           1       0.96      0.93      0.95        57

    accuracy                           0.96       146
   macro avg       0.96      0.95      0.96       146
weighted avg       0.96      0.96      0.96       146

              precision    recall  f1-score   support

           0       0.99      0.98      0.98        87
           1       0.97      0.98      0.98        62

    accuracy                           0.98       149
   macro avg       0.98      0.98      0.98       149
weighted avg       0.98      0.98      0.98       149

,0,1,2,3,0_above_baseline,1_above_baseline,2_above_baseline,3_above_baseline
gyro_std,0.513386,0.502571,0.499688,0.507187,yes,yes,no,yes
raw_accel_mean,0.486614,0.497429,0.500312,0.492813,no,no,yes,no

In [22]:
depths = list(range(1, 10, 1))
estimators = list(range(20, 60, 1))

param_grid = {"max_depth": depths, "n_estimators": estimators}

grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=1),
    param_grid=param_grid,
    cv=sgkf,
    scoring="accuracy",
    n_jobs=-1,
)

grid_search.fit(X, y, groups=groups)

GridSearchCV(cv=StratifiedGroupKFold(n_splits=4, random_state=None, shuffle=False),
             estimator=RandomForestClassifier(random_state=1), n_jobs=-1,
             param_grid={'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9],
                         'n_estimators': [20, 21, 22, 23, 24, 25, 26, 27, 28,
                                          29, 30, 31, 32, 33, 34, 35, 36, 37,
                                          38, 39, 40, 41, 42, 43, 44, 45, 46,
                                          47, 48, 49, ...]},
             scoring='accuracy')

In [23]:
clf = RandomForestClassifier(max_depth=2, n_estimators=47, random_state=1)
clf.fit(X, y)

RandomForestClassifier(max_depth=2, n_estimators=47, random_state=1)

In [24]:
model_src = m2c.export_to_dart(clf)

with open("../models/binary_intensity_classifier.dart", "w") as file:
    file.write(model_src)